default: true
MD003:
  style: atx
MD007:
  indent: 4
MD013:
  line_length: 400
MD033: false
MD034: false
no-inline-html:
  allowed_elements:
    - br
    - img
no-hard-tabs: false
whitespace: false
MD013:
  line_length: 150
