on: [push]
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    
    - uses: azure/docker-login@v1
      with:
        login-server: mycontainerregistry1126.azurecr.io
        username: ${{ secrets.acr_mycontainerregistry1126_username }}
        password: ${{ secrets.acr_mycontainerregistry1126_password }}
    
    - name: Build and push image to ACR
      id: build-image
      run: |
        docker build "$GITHUB_WORKSPACE/chunks/lang-java" -f  "chunks/lang-java/Dockerfile" -t mycontainerregistry1126.azurecr.io/akscontosovideo:${{ github.sha }} --label dockerfile-path=chunks/lang-java/Dockerfile
        docker push mycontainerregistry1126.azurecr.io/akscontosovideo:${{ github.sha }}
    
    - uses: azure/k8s-set-context@v1
      with:
         kubeconfig: ${{ secrets.aks_akscontosovideo_kubeConfig }}
      id: login
    
    - name: Create namespace
      run: |
        namespacePresent=`kubectl get namespace | grep aks-contoso-video8aaf | wc -l`
        if [ $namespacePresent -eq 0 ]
        then
            echo `kubectl create namespace aks-contoso-video8aaf`
        fi

    - uses: azure/k8s-create-secret@v1
      with:
        namespace: aks-contoso-video8aaf
        container-registry-url: mycontainerregistry1126.azurecr.io
        container-registry-username: ${{ secrets.acr_mycontainerregistry1126_username }}
        container-registry-password: ${{ secrets.acr_mycontainerregistry1126_password }}
        secret-name: akscontosovidockerauth
       
    - uses: azure/k8s-deploy@v1.2
      with:
        namespace: aks-contoso-video8aaf
        manifests: |
          manifests/deployment.yml
          manifests/service.yml
          manifests/ingress.yml
        images: |
          mycontainerregistry1126.azurecr.io/akscontosovideo:${{ github.sha }}
        imagepullsecrets: |
          akscontosovidockerauth
